{"level":"error","message":"Unable to connect to database: role \"postgresql\" does not exist","name":"SequelizeConnectionError","original":{"code":"28000","file":"miscinit.c","length":102,"line":"755","name":"error","routine":"InitializeSessionUserId","severity":"FATAL"},"parent":{"code":"28000","file":"miscinit.c","length":102,"line":"755","name":"error","routine":"InitializeSessionUserId","severity":"FATAL"},"service":"healthweb-clone","stack":"SequelizeConnectionError: role \"postgresql\" does not exist\n    at Client._connectionCallback (/Users/frida/Documents/Projects/CloudNode-/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/Users/frida/Documents/Projects/CloudNode-/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/Users/frida/Documents/Projects/CloudNode-/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at /Users/frida/Documents/Projects/CloudNode-/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/Users/frida/Documents/Projects/CloudNode-/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/Users/frida/Documents/Projects/CloudNode-/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-14T18:53:27.760Z"}
{"level":"error","message":"Database sync failed: role \"postgresql\" does not exist","name":"SequelizeConnectionError","original":{"code":"28000","file":"miscinit.c","length":102,"line":"755","name":"error","routine":"InitializeSessionUserId","severity":"FATAL"},"parent":{"code":"28000","file":"miscinit.c","length":102,"line":"755","name":"error","routine":"InitializeSessionUserId","severity":"FATAL"},"service":"healthweb-clone","stack":"SequelizeConnectionError: role \"postgresql\" does not exist\n    at Client._connectionCallback (/Users/frida/Documents/Projects/CloudNode-/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/Users/frida/Documents/Projects/CloudNode-/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/Users/frida/Documents/Projects/CloudNode-/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at /Users/frida/Documents/Projects/CloudNode-/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/Users/frida/Documents/Projects/CloudNode-/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/Users/frida/Documents/Projects/CloudNode-/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-14T18:53:27.762Z"}
{"level":"error","message":"Unable to connect to database: database \"frida\" does not exist","name":"SequelizeConnectionError","original":{"code":"3D000","file":"postinit.c","length":90,"line":"890","name":"error","routine":"InitPostgres","severity":"FATAL"},"parent":{"code":"3D000","file":"postinit.c","length":90,"line":"890","name":"error","routine":"InitPostgres","severity":"FATAL"},"service":"healthweb-clone","stack":"SequelizeConnectionError: database \"frida\" does not exist\n    at Client._connectionCallback (/Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at /Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-14T19:06:11.747Z"}
{"level":"error","message":"Database sync failed: database \"frida\" does not exist","name":"SequelizeConnectionError","original":{"code":"3D000","file":"postinit.c","length":90,"line":"890","name":"error","routine":"InitPostgres","severity":"FATAL"},"parent":{"code":"3D000","file":"postinit.c","length":90,"line":"890","name":"error","routine":"InitPostgres","severity":"FATAL"},"service":"healthweb-clone","stack":"SequelizeConnectionError: database \"frida\" does not exist\n    at Client._connectionCallback (/Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/pg/lib/client.js:336:19)\n    at Client._handleErrorMessage (/Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/pg/lib/client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at /Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/Users/frida/Documents/Projects/CloudNode-/healthweb/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-14T19:06:11.750Z"}
